version: '3.8'

services:


  minio:
    image: quay.io/minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: minio-master
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: unless-stopped

  minio2:
    image: quay.io/minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: minio2
    env_file:
      - .env
    ports:
      - '9003:9000'
      - '9004:9001'
    command: server /data --console-address ":9001"
    restart: unless-stopped

  minio3:
    image: quay.io/minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: minio3
    env_file:
      - .env
    ports:
      - '9005:9000'
      - '9006:9001'
    command: server /data --console-address ":9001"
    restart: unless-stopped

