"""initial migration

Revision ID: 30736bfd9ca1
Revises: 
Create Date: 2023-04-17 14:46:55.144024

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "30736bfd9ca1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "films",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "s3storages",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("ip_address", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip_address"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "films_s3storages",
        sa.Column("film_id", sa.Uuid(), nullable=False),
        sa.Column("s3storage_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["film_id"], ["films.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["s3storage_id"], ["s3storages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("film_id", "s3storage_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("films_s3storages")
    op.drop_table("s3storages")
    op.drop_table("films")
    # ### end Alembic commands ###
