services:
  broker-1:
    ports:
      - "39092:39092"

  etl_ugc:
    build:
      context: ./etl_ugc
      dockerfile: ./docker/Dockerfile

  clickhouse-node1:
    ports:
      - "8123:8123"
      - "9100:9000"

  ugc_service:
    build:
      context: ./ugc
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - ./ugc/src:/opt/app
    ports:
        - "8001:8001"

  auth:
    build:
      context: auth
      dockerfile: ./docker/Dockerfile
      target: development
    ports:
      - "5000:5000"

  redis_auth:
    ports:
      - "${REDIS_AUTH_PORT}:6379"

  postgres_auth:
    ports:
      - "${PG_AUTH_PORT}:5432"

  backend:
    restart: "always"
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
      target: development
    container_name: backend
    volumes:
      - ./backend/src/:/opt/app/
    ports:
      - "8000:8000"

  redis_backend:
    ports:
      - "${REDIS_BACKEND_PORT}:6379"

  elasticsearch_movies:
    ports:
      - "${ELK_MOVIES_PORT}:9200"

  minio-0:
    ports:
     - "9000:9000"
     - "9001:9001"
    networks:
      default:
        ipv4_address: 172.18.0.10

  minio-1:
    ports:
      - "9010:9000"
      - "9011:9001"
    networks:
      default:
        ipv4_address: 172.18.0.11

  minio-2:
    ports:
      - "9020:9000"
      - "9021:9001"
    networks:
      default:
        ipv4_address: 172.18.0.12

  prometheus:
    ports:
      - "9090:9090"

  admin_movies:
    ports:
      - "${DJANGO_MOVIES_PORT}:8000"

  postgres_movies:
    ports:
      - "5436:5432"

  load-service:
    ports:
      - "8010:8000"

  dashboard:
    ports:
      - "5555:5555"

  routing-service:
    ports:
      - "8008:8000"

  sync-service:
    ports:
      - "8012:8000"

  postgres_sync:
    ports:
      - "${PG_SYNC_PORT}:5432"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1